# Generated by Django 4.1 on 2022-11-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="advertising",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=256)),
                ("email", models.CharField(max_length=128)),
                ("state", models.CharField(max_length=128)),
                ("category", models.CharField(max_length=128)),
                ("image", models.ImageField(upload_to="media/")),
            ],
        ),
    ]
