# Generated by Django 4.1 on 2022-11-08 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_advertising", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertising",
            name="state",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ]
            ),
        ),
    ]
