# Generated by Django 4.1 on 2022-11-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "exchange_advertising",
            "0003_alter_advertising_category_alter_advertising_state",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertising",
            name="image",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
