# Generated by Django 4.1 on 2022-11-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_advertising", "0004_alter_advertising_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertising",
            name="image",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
