# Generated by Django 4.1 on 2022-11-17 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_advertising", "0002_alter_advertising_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertising",
            name="category",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="advertising",
            name="state",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
